# Stage 1: Build the app
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Run the app
FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=builder /app/target/cropserver-0.0.1-SNAPSHOT.jar cropserver.jar


EXPOSE 8080


ENTRYPOINT ["java", "-jar", "cropserver.jar"]